services:
  # Web Service (Your Application)
  - type: web
    name: sunnah-skills-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run db:push; npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sunnah-skills-db
          property: connectionString
    healthCheckPath: /health
    
  # PostgreSQL Database
  - type: pgsql
    name: sunnah-skills-db
    databaseName: sunnah_skills
    user: sunnah_skills_user